<?php
$config = array('clientes' => array(array(
                                	'field'=>'nomeCliente',
                                	'label'=>'Nome',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'documento',
                                	'label'=>'CPF/CNPJ',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'documento2',
                                	'label'=>'RG/IE',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'telefone',
                                	'label'=>'Telefone',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'telefone2',
                                	'label'=>'Telefone 2',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'email',
                                	'label'=>'Email',
                                	'rules'=>'trim|valid_email|xss_clean'
                                ),
								array(
                                	'field'=>'rua',
                                	'label'=>'Rua',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'numero',
                                	'label'=>'Número',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'bairro',
                                	'label'=>'Bairro',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'cidade',
                                	'label'=>'Cidade',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'estado',
                                	'label'=>'Estado',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'cep',
                                	'label'=>'CEP',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'limite',
                                	'label'=>'Limite',
                                	'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'observacaoCliente',
                                	'label'=>'Observação',
                                	'rules'=>'trim|xss_clean'
                                ))
                ,
                'servicos' => array(array(
                                    'field'=>'nome',
                                    'label'=>'Nome',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'descricao',
                                    'label'=>'',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'preco',
                                    'label'=>'',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'grupo',
                                    'label'=>'Grupo',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'subgrupo',
                                    'label'=>'SubGrupo',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'categoria',
                                    'label'=>'Categoria',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'classe',
                                    'label'=>'Classe',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'tipo',
                                    'label'=>'Tipo',
                                    'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'observacaoServico',
                                	'label'=>'Observação',
                                	'rules'=>'trim|xss_clean'
                                ))
                ,
                'produtos' => array(array(
                                    'field'=>'descricao',
                                    'label'=>'',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'unidade',
                                    'label'=>'Unidade',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'precoCompra',
                                    'label'=>'Preo de Compra',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'precoVenda',
                                    'label'=>'Preo de Venda',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'estoque',
                                    'label'=>'Estoque',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'estoqueMinimo',
                                    'label'=>'Estoque Mnimo',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'grupo',
                                    'label'=>'Grupo',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'subgrupo',
                                    'label'=>'SubGrupo',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'categoria',
                                    'label'=>'Categoria',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'classe',
                                    'label'=>'Classe',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'tipo',
                                    'label'=>'Tipo',
                                    'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'observacaoProduto',
                                	'label'=>'Observação',
                                	'rules'=>'trim|xss_clean'
                                ))
                ,
                'usuarios' => array(array(
                                    'field'=>'nome',
                                    'label'=>'Nome',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'rg',
                                    'label'=>'RG',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'cpf',
                                    'label'=>'CPF',
                                    'rules'=>'trim|xss_clean|is_unique[usuarios.cpf]'
                                ),
                                array(
                                    'field'=>'rua',
                                    'label'=>'Rua',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'numero',
                                    'label'=>'Numero',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'bairro',
                                    'label'=>'Bairro',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'cidade',
                                    'label'=>'Cidade',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'estado',
                                    'label'=>'Estado',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'email',
                                    'label'=>'Email',
                                    'rules'=>'trim|valid_email|xss_clean'
                                ),
                                array(
                                    'field'=>'senha',
                                    'label'=>'Senha',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'telefone',
                                    'label'=>'Telefone',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'celular',
                                    'label'=>'Celular',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'situacao',
                                    'label'=>'Situacao',
                                    'rules'=>'trim|xss_clean'
                                ),
								array(
                                	'field'=>'observacaoUsuario',
                                	'label'=>'Observação',
                                	'rules'=>'trim|xss_clean'
                                ))
                ,      
                'os' => array(array(
                                    'field'=>'dataInicial',
                                    'label'=>'DataInicial',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'dataFinal',
                                    'label'=>'DataFinal',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'garantia',
                                    'label'=>'Garantia',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'descricaoProduto',
                                    'label'=>'DescricaoProduto',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'defeito',
                                    'label'=>'Defeito',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'status',
                                    'label'=>'Status',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'observacoes',
                                    'label'=>'Observacoes',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'clientes_id',
                                    'label'=>'clientes',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'usuarios_id',
                                    'label'=>'usuarios_id',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'laudoTecnico',
                                    'label'=>'Laudo Tecnico',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'documentoOs',
                                    'label'=>'Documento',
                                    'rules'=>'trim|xss_clean'
                                ))

                  ,
				'tiposUsuario' => array(array(
                                	'field'=>'nomeTipo',
                                	'label'=>'NomeTipo',
                                	'rules'=>'required|trim|xss_clean'
                                ),
								array(
                                	'field'=>'situacao',
                                	'label'=>'Situacao',
                                	'rules'=>'required|trim|xss_clean'
                                ))

                ,
                'receita' => array(array(
                                    'field'=>'descricao',
                                    'label'=>'Descrição',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'valor',
                                    'label'=>'Valor',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'vencimento',
                                    'label'=>'Data Vencimento',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                        
                                array(
                                    'field'=>'cliente',
                                    'label'=>'Pessoa',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'tipo',
                                    'label'=>'Tipo',
                                    'rules'=>'required|trim|xss_clean'
                                ))
                ,
                'despesa' => array(array(
                                    'field'=>'descricao',
                                    'label'=>'Descrição',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'valor',
                                    'label'=>'Valor',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'vencimento',
                                    'label'=>'Data Vencimento',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'fornecedor',
                                    'label'=>'Fornecedor',
                                    'rules'=>'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'tipo',
                                    'label'=>'Tipo',
                                    'rules'=>'required|trim|xss_clean'
                                ))
                ,
                'vendas' => array(array(

                                    'field' => 'dataVenda',
                                    'label' => 'Data da Venda',
                                    'rules' => 'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'clientes_id',
                                    'label'=>'clientes',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'usuarios_id',
                                    'label'=>'usuarios_id',
                                    'rules'=>'trim|xss_clean|required'
                                ),
								array(
                                	'field'=>'observacaoVenda',
                                	'label'=>'Observação',
                                	'rules'=>'trim|xss_clean'
                                ))
                ,
                'compras' => array(array(

                                    'field' => 'dataCompra',
                                    'label' => 'Data da Compra',
                                    'rules' => 'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'clientes_id',
                                    'label'=>'clientes',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'usuarios_id',
                                    'label'=>'usuarios_id',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'observacaoCompra',
                                    'label'=>'Observação',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'documentoCompra',
                                    'label'=>'Documento',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'dataDocumentoCompra',
                                    'label'=>'Data documento',
                                    'rules'=>'trim|xss_clean'
                                ))
                ,
                'entrada' => array(array(

                                    'field' => 'data',
                                    'label' => 'data',
                                    'rules' => 'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'tipo',
                                    'label'=>'tipo',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'documento',
                                    'label'=>'documento',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'serie',
                                    'label'=>'serie',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'produtosIncluir_id',
                                    'label'=>'produto',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'quantidade',
                                    'label'=>'quantidade',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'valor',
                                    'label'=>'valor',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'subtotal',
                                    'label'=>'SubTotal',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'observacao',
                                    'label'=>'observacaoEstoque',
                                    'rules'=>'trim|xss_clean'
                                ))
                ,
                'saida' => array(array(

                                    'field' => 'data',
                                    'label' => 'data',
                                    'rules' => 'required|trim|xss_clean'
                                ),
                                array(
                                    'field'=>'tipo',
                                    'label'=>'tipo',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'documento',
                                    'label'=>'documento',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'serie',
                                    'label'=>'serie',
                                    'rules'=>'trim|xss_clean'
                                ),
                                array(
                                    'field'=>'produtos2Incluir_id',
                                    'label'=>'produto',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'quantidade',
                                    'label'=>'quantidade',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'valor',
                                    'label'=>'valor',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'subtotal',
                                    'label'=>'SubTotal',
                                    'rules'=>'trim|xss_clean|required'
                                ),
                                array(
                                    'field'=>'observacao',
                                    'label'=>'observacaoEstoque',
                                    'rules'=>'trim|xss_clean'
                                ))
								
		);
			   